#!/usr/bin/env zsh

# curl https://www.gutenberg.org/files/4300/4300-0.txt -o /tmp/ulysses.txt

bench "ja '(+)|0 {%/Bloom/}{1}' -i /tmp/ulysses.txt" \
    "original-awk '/Bloom/ { total += 1; } END { print total }' /tmp/ulysses.txt" \
    "gawk '/Bloom/ { total += 1; } END { print total }' /tmp/ulysses.txt" \
    "mawk '/Bloom/ { total += 1; } END { print total }' /tmp/ulysses.txt" \
    "busybox awk '/Bloom/ { total += 1; } END { print total }' /tmp/ulysses.txt" 

bench "ja run examples/span.jac -i examples/span.txt" \
    "original-awk -f examples/span.awk examples/span.txt" \
    "gawk -f examples/span.awk examples/span.txt" \
    "mawk -f examples/span.awk examples/span.txt" \
    "busybox awk -f examples/span.awk examples/span.txt"
